### ISSUE TITLE
....

### ISSUE THREAD

**Issue by kainzhang** [billionray/ZZULI-healthreport#35]
你好你好 👋

**Comment by L-Suit** [comment]
19的来瞻仰一下，但现在连接跳不出来啊，服务器没搭好吗

**Comment by billionray** [comment]
@kainzhang 你好

**Comment by billionray** [comment]
@L-Suit http://kys.zzuli.edu.cn/cas/login?这个页面有改版，需要重新适配。
但现在似乎全校已经暂停打卡了？所以在我们学院重新开始打卡前没有再次适配的欲望....
如果你有意适配，欢迎pr

**Comment by billionray** [comment]
@L-Suit 部分学院已经重新要求打卡，我们已经完成适配，欢迎继续使用
