### ISSUE TITLE
这是哪位大佬写的？

### ISSUE THREAD

**Issue by huigang39** [billionray/ZZULI-healthreport#44]
如题

**Comment by xwwwb** [comment]
仓库是谁的就是谁写的👍

**Comment by billionray** [comment]
你可以在 contributors 页面查看贡献者们的贡献比例https://github.com/billionray/ZZULI-healthreport/graphs/contributors

**Comment by billionray** [comment]
还有，嘉心糖请关注七海nana7mi，成为脆脆鲨
