### ISSUE TITLE
发邮件问题

### ISSUE THREAD

**Issue by qianfuzhuang** [billionray/ZZULI-healthreport#49]
哥，问一下那个发邮件的是需要额外配置什么吗？一直没明白，本地运行没有问题，但是在github上他就报错

**Comment by billionray** [comment]
请根据[此链接](https://xwwwb.github.io/zzulidakadocs/#/github_action?id=%e5%8f%af%e9%80%89%ef%bc%9a%e9%82%ae%e7%ae%b1%e6%8f%90%e9%86%92)再次检查并更新一下您的secrets
