### ISSUE TITLE
多高校打卡合作邀请

### ISSUE THREAD

**Issue by mrcaidev** [billionray/ZZULI-healthreport#51]
朋友您好！

我是[电子科技大学自动打卡](https://github.com/mrcaidev/thermoflash)项目的作者，现欲开发一款各高校通用的、基于 GitHub Actions 的自动打卡工具；目前框架与主程序都已初步搭建完毕，后续的开发者只需要编写插件即可。

一位朋友向我推荐了您的项目。拜读之后，我觉得您的代码水平与逻辑都十分地优秀且可靠，不知您是否愿意了解一下[上述的项目](https://github.com/mrcaidev/thermoflash)；如果能参与开发，更是我的荣幸。您随时可以通过 QQ 联系我：1014305148。

期待与您的合作，相互学习、共同进步！

**Comment by mrcaidev** [comment]
抱歉再次打扰！经过这两天与其它学校的交涉与慎重考虑之后，我认为该项目在难度与合法性上均面临一定的挑战，于是决定终止该计划，对您造成的不便与困扰敬请谅解！

**Comment by billionray** [comment]
收到，很遗憾没能推动
