### ISSUE TITLE
2022年7月19日打卡表单发生变化导致打卡失败

### ISSUE THREAD

**Issue by hash070** [billionray/zzuli-healthreport#54]
这位大佬的仓库今天刚刚适配了最新的打卡，感觉可以参考一下：[https://github.com/cxOrz/zzuli-autoclockin](https://github.com/cxOrz/zzuli-autoclockin)
然后本鼠鼠太菜了，代码看的不是很懂，就没敢乱改
![image](https://user-images.githubusercontent.com/62081013/179641057-06ca8cd3-456b-404c-a376-60f5cdbc705d.png)

附：新的表单提交界面：
![image](https://user-images.githubusercontent.com/62081013/179640655-6e864c1f-500a-4bee-8025-d375d11c2231.png)
![image](https://user-images.githubusercontent.com/62081013/179640670-8ab40477-a7ed-4b54-af32-f2ad485b6451.png)
![image](https://user-images.githubusercontent.com/62081013/179640681-82e71b9b-579e-48aa-940a-94432bbbb0e0.png)

**Comment by billionray** [comment]
谢谢您，我刚刚适配好了

**Comment by billionray** [comment]
我参照您 https://github.com/cxOrz/zzuli-autoclockin/commit/c72999d4e45cd4beeec8d011e8a5872dd848696b 的commit进行适配，再次感谢！

**Comment by hash070** [comment]
Thanks for your work!
Your program really helped my friends and me a lot!

**Comment by billionray** [comment]
It's my pleasure.

**Comment by billionray** [comment]
非常抱歉由于我的失误导致昨天的commit不能正确提交表单，请合并最新的commit
