### ISSUE TITLE
完了，身体异常了

### ISSUE THREAD

**Issue by yijrqz777** [billionray/zzuli-healthreport#58]
完了，身体异常了，大佬是新问题还是我的设置有问题，辅导员找了

**Comment by 1920508375** [comment]
一样 同问

**Comment by hash070** [comment]
把最新./app/data.py复制粘贴过去应该就OK了。

**Comment by yijrqz777** [comment]
你是一切正常的嘛，辅导员没找你吗

**Comment by q184724842** [comment]
这个 我三天更新的 刚才我看他两天前又更了一次  我刚刚又更了 也不知道行不行

**Comment by billionray** [comment]
@yijrqz777 @1920508375 @q184724842 @hash070 请合并最新代码，抱歉给您带来的不便

**Comment by 1920508375** [comment]
@billionray 
没有没有 感谢作者大大 辛苦了

**Comment by xwwwb** [comment]
出现一切异常，就说我不知道 可能是填的时候没看好
